update compiler version and remove deprecated entities
uport-project/ethr-did-registry pull request #45
Opened 2021-11-30 16:53 UTC by nichonien

This PR contains changes : 

1. Upgrade compiler version
2. Replaces `now` with `block.timestamp`
3. Replaces `byte` with `bytes1`
4. Updates `keccak256` implementation to one parameter implementation (latest version)
5. Updates `0x0` address to full length address

2021-12-04 15:37 UTC, nichonien commented
@mirceanis Did you get a chance to look the at PR?

2021-12-07 12:39 UTC, mirceanis requested changes
Excellent work.

It took me a while to test this out since the existing test harness doesn't work on my machine any more.
We need to upgrade the test automation here as well if we want to keep improving the contract(s).

I made some suggestions regarding the way the message is hashed in the `change/add/remove*Signed()` methods, for maintaining compatibility with existing codebases.

Using `abi.encodePacked` allows the caller to use simple concatenation of byte arrays instead of doing RLP encoding of arguments.
Also, since there is at most one variable-length array parameter, the [warning in the solidity docs](https://docs.soliditylang.org/en/v0.8.10/abi-spec.html#non-standard-packed-mode) does not apply.

2021-12-07 12:39 UTC, mirceanis commented on contracts/EthereumDIDRegistry.sol
> +    bytes32 hash = keccak256(abi.encode(bytes1(0x19), bytes1(0), this, nonce[identityOwner(identity)], identity, "changeOwner", newOwner));
To preserve compatibility with existing codebases, this should be `encodePacked`
```suggestion
    bytes32 hash = keccak256(abi.encodePacked(bytes1(0x19), bytes1(0), this, nonce[identityOwner(identity)], identity, "changeOwner", newOwner));
```

2021-12-07 12:39 UTC, mirceanis commented on contracts/EthereumDIDRegistry.sol
> +    bytes32 hash = keccak256(abi.encode(bytes1(0x19), bytes1(0), this, nonce[identityOwner(identity)], identity, "addDelegate", delegateType, delegate, validity));
To preserve compatibility with existing codebases, this should be `encodePacked`
```suggestion
    bytes32 hash = keccak256(abi.encodePacked(bytes1(0x19), bytes1(0), this, nonce[identityOwner(identity)], identity, "addDelegate", delegateType, delegate, validity));
```

2021-12-07 12:39 UTC, mirceanis commented on contracts/EthereumDIDRegistry.sol
> +    bytes32 hash = keccak256(abi.encode(bytes1(0x19), bytes1(0), this, nonce[identityOwner(identity)], identity, "revokeDelegate", delegateType, delegate));
To preserve compatibility with existing codebases, this should be `encodePacked`
```suggestion
    bytes32 hash = keccak256(abi.encodePacked(bytes1(0x19), bytes1(0), this, nonce[identityOwner(identity)], identity, "revokeDelegate", delegateType, delegate));
```

2021-12-07 12:39 UTC, mirceanis commented on contracts/EthereumDIDRegistry.sol
> +    bytes32 hash = keccak256(abi.encode(bytes1(0x19), bytes1(0), this, nonce[identityOwner(identity)], identity, "setAttribute", name, value, validity));
To preserve compatibility with existing codebases, this should be `encodePacked`
```suggestion
    bytes32 hash = keccak256(abi.encodePacked(bytes1(0x19), bytes1(0), this, nonce[identityOwner(identity)], identity, "setAttribute", name, value, validity));
```

2021-12-07 12:39 UTC, mirceanis commented on contracts/EthereumDIDRegistry.sol
> +    bytes32 hash = keccak256(abi.encode(bytes1(0x19), bytes1(0), this, nonce[identityOwner(identity)], identity, "revokeDelegate", delegateType, delegate));
To preserve compatibility with existing codebases, this should be `encodePacked`
```suggestion
    bytes32 hash = keccak256(abi.encodePacked(bytes1(0x19), bytes1(0), this, nonce[identityOwner(identity)], identity, "revokeDelegate", delegateType, delegate));
```

2021-12-07 12:39 UTC, mirceanis commented on contracts/EthereumDIDRegistry.sol
> +    bytes32 hash = keccak256(abi.encode(bytes1(0x19), bytes1(0), this, nonce[identityOwner(identity)], identity, "revokeAttribute", name, value));
To preserve compatibility with existing codebases, this should be `encodePacked`
```suggestion
    bytes32 hash = keccak256(abi.encodePacked(bytes1(0x19), bytes1(0), this, nonce[identityOwner(identity)], identity, "revokeAttribute", name, value)); 
```

2021-12-07 20:30 UTC, mirceanis approved these changes
Looks great!

Thank you for contributing

2021-12-07 20:31 UTC, merged

2021-12-07 20:39 UTC, mirceanis commented
BTW, I have started a governance topic about did:ethr upgrades on our discord: https://discord.gg/MTeTAwSYe7

Feel free to join and share your thoughts.